### ISSUE TITLE
Add https://search.chemicals-in-the-water.eu

### ISSUE THREAD

**Issue by somerandomusername666** [searxng/searx-instances#101]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Your instance will be removed if you don't respect this rule.

### Bot protection

No, I have not installed a bot protection and I do recognize that without one, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

### Comment

Back up again after moving vps, ipv6 should work

**Comment by unixfox** [comment]
Your uptime has been very low lately, that's why we removed your instance. 64% of uptime: https://github.com/searxng/searx-instances-uptime/blob/0ed8ee79baa3349f7b0038412afd918ba71205db/api/search-chemicals-in-the-water-eu/uptime.json

Next time you have a big downtime, ask to temporarily remove your instance from the list.

If we find again that your instance has a bad uptime, we will permanently remove your instance from the list.

**Comment by somerandomusername666** [comment]
Won't happen again, I will let it know beforehand if there's gonna be a big
maintenance again.
