### ISSUE TITLE
https://zonghe.com

### ISSUE THREAD

**Issue by kevinwangsl99** [searxng/searx-instances#12]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

### Bot protection

Yes, I have installed filtron (rules.json from searx-docker).

### Source code URL

https://github.com/kevinwangsl99/zonghe

**Comment by unixfox** [comment]
Hello,

Your filtron rules are not installed correctly, I'm able to do an infinite amount of requests (more than 5 requests) on the JSON results: https://zonghe.com/search?category_general=1&q=ok&pageno=1&time_range=None&language=zh-CN&format=json

You should look into fixing them.

This is just an advice and if you don't want to follow it I can add your instance anyway.

**Comment by unixfox** [comment]
Closing due to a lack of replies. Please reopen and respond to my question.

**Comment by kevinwangsl99** [comment]
I have installed the filtron again. does it look good now?

**Comment by unixfox** [comment]
Filtron is not enough, you need to use these rules: https://github.com/searx/searx-docker/blob/master/rules.json

**Comment by kevinwangsl99** [comment]
I didn't install the site by docker. I followed this way to setup the filtron: $ go get github.com/searxng/filtron
$ "$GOPATH/bin/filtron" --help, and I don't know how to do next.

**Comment by unixfox** [comment]
Hosting a public instance is not an easy task, if you don't know much about Linux you are going to have some difficulties maintaining your instance for the public.

Are you sure you really want to offer your instance to the public?

**Comment by kevinwangsl99** [comment]
I definitely want to go pubulic. I am using Apache. Upload the rules.json. and ./filtron -rules rules.json, it seems deploied well. Is it OK now?

**Comment by unixfox** [comment]
No, it's not good, I told you how to test. Refresh 5 times this page: https://zonghe.com/search?category_general=1&q=ok&pageno=1&time_range=None&language=zh-CN&format=json and if you don't see "Rate limit exceeded, try again later." then the rules are not applied correctly.

Again, based on the knowledge that you have shown, I really don't recommend you to host a public instance because there are a lot of bad actors that will try to abuse your instance, and you won't be able to stop them. This will thus decrease the usability/stability of your searx instance.

**Comment by unixfox** [comment]
Closing due to the lack of replies.
