### ISSUE TITLE
https://searx.rubbeldiekatz.nohost.me/searx/

### ISSUE THREAD

**Issue by magotar** [searxng/searx-instances#162]
### Requirements

- [X] It is my instance.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime or notify us [here](https://github.com/searxng/searx-instances/discussions/categories/report-instance-downtime) for a short downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)

### Bot protection

No, I have not installed a bot protection and I do recognize that without one, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

### Comment

Contact magotar@rubbeldiekatz.info

**Comment by tiekoetter** [comment]
Hi @magotar
The [TLS](https://cryptcheck.fr/https/searx.rubbeldiekatz.nohost.me) grade of your instance is not optimal.
The [CSP](https://observatory.mozilla.org/analyze/searx.rubbeldiekatz.nohost.me) grade is also not optimal because your root path redirects to a different website.

If you are ok with your instance being ranked lower, according to the grades, can your instance be added regardless.

**Comment by unixfox** [comment]
Closing due to lack of replies.
