### ISSUE TITLE
Add https://sear.r-ay.co

### ISSUE THREAD

**Issue by rayooss** [searxng/searx-instances#174]
### Requirements

- [X] It is my instance.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime or notify us [here](https://github.com/searxng/searx-instances/discussions/categories/report-instance-downtime) for a short downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)

### Bot protection

No, I have not installed a bot protection and I do recognize that without one, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by ononoki1** [comment]
There are some issues with your instance. __They can all be ignored if you do not mind being ranked lower on searx.space.__

1. Your [TLS](https://cryptcheck.fr/https/sear.r-ay.co) grade is not optimal. You can keep only `ECDHE-ECDSA-AES128-GCM-SHA256`, `ECDHE-ECDSA-AES256-GCM-SHA384` and `ECDHE-ECDSA-CHACHA20-POLY1305` ciphers for TLSv1.2 to get A+.
2. Your [CSP](https://observatory.mozilla.org/analyze/sear.r-ay.co) grade is not optimal. You can set proper HSTS and CSP header to get A+. An example for HSTS is [here](https://github.com/searxng/searxng-docker/blob/f2f9e2ad086c68443c3457a82cf2e368aaa4bc99/Caddyfile#L37), and CSP is [here](https://github.com/searxng/searxng-docker/blob/f2f9e2ad086c68443c3457a82cf2e368aaa4bc99/Caddyfile#L85).

If you want to fix these issues before adding your instance to searx.space, just do it and notify us when finished. Otherwise, tell us you do not want to fix them and we will add your instance now.

**Comment by rayooss** [comment]
不介意这些问题，立即添加吧

**Comment by unixfox** [comment]
@rayooss While @ononoki1 can understand Chinese, please write in English (even with a translator) because not everyone does understand Chinese.

**Comment by rayooss** [comment]
Don't mind these questions, please add them now.
