### ISSUE TITLE
Edit https://searxng.nicfab.it

### ISSUE THREAD

**Issue by nicfab** [searxng/searx-instances#199]
Hi!
I changed the domain name from nicfab.it **to=>** nicfab.eu
**So, the instance now is https://searxng.nicfab.eu** 
I kindly ask you to modify the URL with the ew one; all the other settings work fine, like the TOR address.

**Comment by return42** [comment]
@nicfab assume you have activated the limiter and your [tor connection](http://lgmekfnpealdqhnctyg3p5fuelpdwnbqbwnl2ickpdoodzatzgz27ryd.onion) is broken since https://github.com/searxng/searxng/pull/2357 has been merged.

The old implementation of the limiter did not care about a valid IP, this has been fixed in the PR / see --> https://docs.searxng.org/src/searx.botdetection.html#x-forwarded-for

To fix your onion service you need to add the HTTP headers (with a valid IP). 

BTW: take into account, that bot blocking is based on static IPs of the bots -> serious bot-blocking is not possible on the onion network.

**Comment by nicfab** [comment]
> @nicfab I assume you have activated the limiter and your [tor connection](http://lgmekfnpealdqhnctyg3p5fuelpdwnbqbwnl2ickpdoodzatzgz27ryd.onion) is broken since [searxng/searxng#2357](https://github.com/searxng/searxng/pull/2357) has been merged.
> 
> The old implementation of the limiter did not care about a valid IP, this has been fixed in the PR / see --> https://docs.searxng.org/src/searx.botdetection.html#x-forwarded-for
> 
> To fix your onion service you need to add the HTTP headers (with a valid IP).
> 
> BTW: take into account, that bot blocking is based on static IPs of the bots -> serious bot-blocking is not possible on the onion network.

Thank you very much.
Are you referring to the `server` directive in `/etc/searxng/settings.yml` or the directive in the NGINX file conf?

**Comment by return42** [comment]
I refer to NGINX setup .. I assume you have a `location` entry for the onion gateway.

Related discussion on matrix https://matrix.to/#/!vxScbLNEAmRvOraXBn:matrix.org/$9h9s3odTKX9-8O36vJOxawefZu8oG101Hd_0g65VSJ0?via=libera.chat&via=matrix.org&via=tchncs.de

**Comment by nicfab** [comment]
> I refer to NGINX setup .. I assume you have a `location` entry for the onion gateway.
> 
> Related discussion on matrix https://matrix.to/#/!vxScbLNEAmRvOraXBn:matrix.org/$9h9s3odTKX9-8O36vJOxawefZu8oG101Hd_0g65VSJ0?via=libera.chat&via=matrix.org&via=tchncs.de

Ok, the block related to the TOR URL in my NGINX file conf is the following, but after restarting NGINX, I received internal server error.
The row commented was the previous setting.

```
server {
        server_name lgmekfnpealdqhnctyg3p5fuelpdwnbqbwnl2ickpdoodzatzgz27ryd.onion;
        location / {

          proxy_pass http://127.0.0.1:8888;

          proxy_set_header   Host             $host;
          proxy_set_header   Connection       $http_connection;

          # see flaskfix.py
          proxy_set_header   X-Scheme         $scheme;
          #proxy_set_header   X-Script-Name    /searxng;

          # see limiter.py
          proxy_set_header   X-Real-IP        $remote_addr;
          proxy_set_header   X-Forwarded-For  'http://lgmekfnpealdqhnctyg3p5fuelpdwnbqbwnl2ickpdoodzatzgz27ryd.onion';
#          proxy_set_header   X-Forwarded-For  'TOR Network';

        }

```

**Comment by nicfab** [comment]
> I refer to NGINX setup .. I assume you have a `location` entry for the onion gateway.
> 
> Related discussion on matrix https://matrix.to/#/!vxScbLNEAmRvOraXBn:matrix.org/$9h9s3odTKX9-8O36vJOxawefZu8oG101Hd_0g65VSJ0?via=libera.chat&via=matrix.org&via=tchncs.de

Solved (I hope).
Thank you again.

**Comment by return42** [comment]
> Solved (I hope).

Yes, it works now -> https://lgmekfnpealdqhnctyg3p5fuelpdwnbqbwnl2ickpdoodzatzgz27ryd.onion/search?q=ip

--- 

My very personal opinion: I don't serve my instance on the onion network, since we can't block bots coming from this gateway .. 

You have to weigh up whether you place more value on the defense against bots -- and thus a more stable instance --, or whether you make your service available via the onion network.

Personally, I think that users of the onion network do not need a SearXNG instance in the onion network, which is why I put more emphasis on the defense against bots.

**Comment by nicfab** [comment]
> > Solved (I hope).
> 
> Yes, it works now -> https://lgmekfnpealdqhnctyg3p5fuelpdwnbqbwnl2ickpdoodzatzgz27ryd.onion/search?q=ip
> 
> My very personal opinion: I don't serve my instance on the onion network, since we can't block bots coming from this gateway ..
> 
> You have to weigh up whether you place more value on the defense against bots -- and thus a more stable instance --, or whether you make your service available via the onion network.
> 
> Personally, I think that users of the onion network do not need a SearXNG instance in the onion network, which is why I put more emphasis on the defense against bots.

Regarding your personal opinion, I respect it, especially from the technical side.
It seems to me that there are many instances that also have a .onion address.
My initial decision was based on the desirability of offering a service with choice for the TOR network as well.
However, I agree with your approach and will adjust to what you developers decide to do for SearXNG, even if each maintainer chooses individuallly.

**Comment by return42** [comment]
Not to be misunderstood: I do not recommend against an onion gateway, I just want to point out that this also brings restrictions, which are in the nature of the onion network (IPs are hidden).
