### ISSUE TITLE
Add https://search.rhscz.eu

### ISSUE THREAD

**Issue by rhsCZ** [searxng/searx-instances#212]
### Requirements

- [X] It is my instance.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime or notify us [here](https://github.com/searxng/searx-instances/discussions/categories/report-instance-downtime) for a short downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)

### Bot protection

Yes, I have enabled the limiter plugin built in SearXNG.

### Comment

changed domain from search.rhscze.cf(#168) to search.rhscz.eu.
so you can delete search.rhscze.cf, or i will create new issue for remove if you require it.
old domain is tempoarily still active until it's removed from list.

**Comment by return42** [comment]
@rhsCZ I assume you have activated the limiter and your [tor connection](http://lgmekfnpealdqhnctyg3p5fuelpdwnbqbwnl2ickpdoodzatzgz27ryd.onion) is broken since https://github.com/searxng/searxng/pull/2357 has been merged.

The old implementation of the limiter did not care about a valid IP, this has been fixed in the PR / see --> https://docs.searxng.org/src/searx.botdetection.html#x-forwarded-for

To fix your onion service you need to add the HTTP headers (with a valid IP). 

BTW: take into account, that bot blocking is based on static IPs of the bots -> serious bot-blocking is not possible on the onion network.

**Comment by unixfox** [comment]
Please consider joining our Matrix room for public instance maintainers by joining our Matrix room: https://matrix.to/#/#searxng:matrix.org
then pinging @\unixfox, @\dalf and @\mrpaulblack for asking to be invited to the Matrix room.
We discuss troubles managing a public instance, sharing some advices (like how to protect against bots), announcing big changes in searxng and more.
