### ISSUE TITLE
Add https://www.safesearch.center

### ISSUE THREAD

**Issue by stephenhodgkiss** [searxng/searx-instances#251]
### Requirements

- [X] It is my instance. I bought the domain myself and I own this domain. Free domains (e.g. Freenom) and shared domains (e.g. noip.com) are not allowed.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime or notify us [here](https://github.com/searxng/searx-instances/discussions/categories/report-instance-downtime) for a short downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I control the final webserver (software) that is serving the requests to the users of my instance. Here is a non-exhaustive list of forbidden hosting types: PaaS, managed (hosting provider controlled) HTTP(S) load balancer (e.g. AWS ALB), Cloudflare, shared Web hosting. TCP load balancer is fine.

### Bot protection

Yes, I have installed another bot protection.

### Source code URL

https://github.com/stephenhodgkiss/searxng-master.git

### Comment

I have installed Fail2Ban and UFW ... is that enough for BOT protection ?

**Comment by unixfox** [comment]
Your git repository for the source code is not accessible or doesn't exist.

**Comment by stephenhodgkiss** [comment]
Apologies, please try again

**Comment by return42** [comment]
> - [X] I do not track the users of my instance with any analytics or tracking software.

The instance itself does not include analytics or tracking software but ships advertising links to tracking pages on every response.

> https://github.com/stephenhodgkiss/searxng-master.git

Is a copy not a real git fork .. the update process is not clear, I assume the instance will not be updated regularly and degrade over the time.

The sources are manipulated in a way that let me assume the owner is not familiar with the development process of of SearXNG https://github.com/searxng/searxng/issues/2003 

Question of mine: Should we really offer links to such questionable instances on searx.space?

@ononoki1 @unixfox .. what do you think? (give me your thumbs up/down)

**Comment by stephenhodgkiss** [comment]
Let me clarify: 

**The instance itself does not include analytics or tracking software but ships advertising links to tracking pages on every response.**
Yes there are banners on the site but they are controlled by ourselves and certainly do not have any analytics or tracking software installed.

**I assume the instance will not be updated regularly and degrade over the time.**
That's is the wrong assumption.

**The sources are manipulated...**
That's a rash statement to make. I reiterate again, we have only changed the GUI such as logos and ensuring these are responsive.

**Question of mine: Should we really offer links to such questionable instances on searx.space?**
Having concerns are understandable and asking questions to determine these points is also fine. The team already looked at the instance and approved it, so let's leave it to them to decide.

**Comment by unixfox** [comment]
> **Question of mine: Should we really offer links to such questionable instances on searx.space?** Having concerns are understandable and asking questions to determine these points is also fine. The team already looked at the instance and approved it, so let's leave it to them to decide.

@return42 is from the same team that review the public instances.

--------

At the time of reviewing the instance (2nd of December), no ads were displayed, the website was like this:

<img src="https://user-images.githubusercontent.com/4016501/205492069-293b7eb7-1512-41eb-8a77-0c28c6356101.png" width="700">

So I was not aware of ads being added after my review.

While I completely understand that running a public instance is not free, we allow customizing the donation link to a specific page in order to compensate for the cost of running a SearXNG instance. You already know about this existing setting because you disabled it: https://github.com/stephenhodgkiss/searxng/commit/674112b49339282b3f6a9ae946b3555c781271b2

What I propose for the time being @stephenhodgkiss, is to not disturb the users of the public SearXNG instances by displaying an ad right at the top of the search page:
<img src="https://user-images.githubusercontent.com/4016501/205492690-56c080e4-90fe-4cae-8094-3ea2a0c92fdf.png" width="700">
because:
- that's annoying for the users, they wouldn't want to use your instance at all, keep in mind that people using SearXNG are the same people that are mainly escaping from Google.com.
- accessibility wise, the banner takes a lot of space on the mobile version.

I'll open a GitHub discussion so that we can talk about the idea of running ads on a public instance.

**Comment by stephenhodgkiss** [comment]
Thank you @unixfox - please see issue #252
