### ISSUE TITLE
http://xng.ushby.org

### ISSUE THREAD

**Issue by jindiggs** [searxng/searx-instances#312]
### Requirements (make sure to read all of them)

- [X] It is my instance. I bought the domain myself and I own this domain. Free domains (e.g. Freenom) and shared domains (e.g. noip.com) are not allowed.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime or notify us [here](https://github.com/searxng/searx-instances/discussions/categories/report-instance-downtime) for a short downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I control the final webserver (software) that is serving the requests to the users of my instance. Here is a non-exhaustive list of forbidden hosting types: PaaS, managed (hosting provider controlled) HTTP(S) load balancer (e.g. AWS ALB), Cloudflare, shared Web hosting. TCP load balancer is fine.

### Bot protection

Yes, I have enabled the limiter plugin built in SearXNG.

**Comment by ononoki1** [comment]
Please at least enable HTTPS for security.

**Comment by jindiggs** [comment]
`Cloudflare` and `Let's Encrypt` asks for a DNS confirmation and domain changes, respectively. 
Can you recommend an SSL that doesn't ask for DNS change and/or domain name, in order for the IP to have an **SSL** ? 

As for @unixfox you can always help rather than laugh.

**Comment by unixfox** [comment]
Like you agreed in the requirements, managing a public instance is not an easy task.

We expect each public instance maintainer that wants their instance in the public list to have good knowledge of managing a public service. If it's your first time doing it, you should know that a public website requires constant maintenance, being able to react against all kinds of different public attack (that can be for example bots) and being able to keep the instance running all the time (at least 90% of the time per month).

We set this high level bar because we want the end users to have good experience, being able to pick an instance that will work on the long run and more.

So based on your question I'm sorry but I don't think you qualify on having your public instance on the list. But don't give up, learn how to setup public services on a Linux server and come back to us when you are done.
There are plenty of tutorial on your preferred search engine when you search for "host website on linux server".

**Comment by jindiggs** [comment]
I asked for such help, to save time and work faster, since SearXNG is not the only thing keeping my hands busy right now. It's cool though, I'll fix this for myself but I don't want it listed anymore. Because just like I have what to learn, let me tell you.. you've got a lot ahead of you too.

**Comment by jindiggs** [comment]
https://xnglive.site - awww [It looks so cute right now !](https://xnglive.site )
<3 But please, don't list it ! <3 I might get jealous of it. after spending much time on it, I got attached to it. It's mine.

**Comment by return42** [comment]
@jindiggs sorry to say, but what you are doing is a misuse of SearXNG

1. You have made significant customizations but have not published your source code.  I point out that by using SearXNG you have agreed to the license terms of the ["GNU Affero General Public License v3.0"](https://github.com/searxng/searxng/blob/master/LICENSE)!

2. The primary goal of SearXNG is to protect the privacy of our users. We invest a lot of time and effort to meet this goal.  Your service destroys this goal by adding various trackers and CDNs (see screenshots below). Please understand that the good reputation of SearXNG must not be associated with such intentions!

**We urge you to eliminate the above deficiencies in a timely manner.**

----

![grafik](https://user-images.githubusercontent.com/554536/229688241-97aa5772-b588-4275-b5d8-97603b375e13.png)

![grafik](https://user-images.githubusercontent.com/554536/229688436-9636d765-5ce6-4c43-b47c-e2ef5e3140f2.png)

**Comment by unixfox** [comment]
@return42 it's very simple double violation of the rules.

Locking the issue...
