### ISSUE TITLE
Remove instance of "Esmail EL BoB"

### ISSUE THREAD

**Issue by MagicLike** [searxng/searx-instances#344]
Esmail is actively forbidding members or supporters of the LGBTQIA+ community to use their services via a TOS document*.
This is absolutely queerphobic and extremely discriminating. Therefore I ask to remove their instance `searx.esmailelbob.xyz` / `searx.esmail5pdn24shtvieloeedh7ehz3nrwcdivnfhfcedl7gf4kwddhkqd.onion` from the list, to not further support their actions.

*See the commit here: https://web.archive.org/web/20230524152815/https://git.esmailelbob.xyz/esmail/upptime/src/branch/master/pri-tos.md

https://github.com/Metastem/wikiless/issues/29#issuecomment-1557613834

**Comment by unixfox** [comment]
Every removal should be linked to a rule violation. The owner has to be then notified of the violation and we ask to solve the issue or the instance gets removed.

I'm not against adding a new rule but I don't know where to draw the line.

A lot of public instances are already blocking a region or a group of people. That can be for blocking bots like this instance who blocked China for reducing the amount of bots in order to bring back a working user experience: https://github.com/searxng/searx-instances/discussions/324#discussioncomment-5732386

We could have a rule stating somewhere around these lines: "you can block a group of people for the only sole reason of protecting your instance or keep a working user experience for the majority of the users of your instance". But then this would be a bit more defined because the term " defending" is still very broad.

**Comment by IF-Adin** [comment]
@unixfox I think that should not be the focus. A defensive action requires evidence. Attacks coming from an ip range are evidence. You can not assign ip ranges to gay people, nor are they likely to organize in such a fashion.

For everything else, there is always the basic human rights to refer to?

**Comment by xbdmHQ** [comment]
these dudes is like the kiwi farm take down, hints why i got backups of mirrors coming in soon, tired of this shit united states country and  these gays etc. we can't do shit, and then we get hushed to stfu and ignore/be quiet

**Comment by unixfox** [comment]
I've opened an issue for the new rule that will be added, please see: https://github.com/searxng/searx-instances/pull/346

**Comment by unixfox** [comment]
Warning sent to the maintainer: https://github.com/searxng/searx-instances/issues/14#issuecomment-1561900563
