### ISSUE TITLE
Add https://search.vojkovic.xyz

### ISSUE THREAD

**Issue by codingbrock** [searxng/searx-instances#40]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

### Bot protection

Yes, I have installed filtron (other rules).

### Source code URL

https://github.com/codingbrock/searxng/

### Comment

I've done some slight changes to the default searx-docker filtron rules. If my filtron rules aren't set up correctly for some reason, please let me know.

**Comment by tiekoetter** [comment]
Your instance doesn't publish its changed source code correctly. It is still linked to https://github.com/searxng/searxng

The version is also broken. Please check if `git show -s --format='%cs-%h'` shows the correct result.

**Comment by codingbrock** [comment]
> Your instance doesn't publish its changed source code correctly. It is still linked to https://github.com/searxng/searxng
> 
> The version is also broken. Please check if `git show -s --format='%cs-%h'` shows the correct result.

git show -s --format='%cs-%h' returns '%cs-eedc006'. I am fairly new to searxng and I'm not sure how to change the version number and how to publish the changed source code. If you could possibly walk me through the steps for both, that would be amazing. Thanks!

**Comment by tiekoetter** [comment]
The source code is defined in the variable `GIT_URL`.

I don't know why `git show` shows the wrong commit date. I have cloned your repository and didn't encounter the issue.

If you are new to SearXNG maybe start with running a public instance based on the searxng/searxng repository instead of your own.

If you want to I can look into this a little further later in the day.

**Comment by codingbrock** [comment]
I've tried for some hours today on changing the version and GIT_URL but every time it doesn't work. Maybe I'm just missing something here... maybe I should try using Docker instead?... I'm really not sure what to do..

I would run my instance from the vanilla repo but, in my opinion, it is significantly more ugly than paul's fork so that would not be preferable. 

If anyone has some guidance for me that would be great.

**Comment by tiekoetter** [comment]
@mrpaulblack

**Comment by mrpaulblack** [comment]
The formatting of the version string in my fork worts differently than upstream SearXNG. I basically clone the entire SearXNG repo in a docker container and after that run the version freeze script from upstream inside the docker container. After that is done I make the changes to some files with the CSS files from my fork... So basically the version is generated from upstream and since my changes a tracked in my fork, I dont get the dirty in the version string and `searx.space` accepts my instance as a fork :+1: 

See:
https://github.com/paulgoio/searxng/blob/735c267164a38dfd6d04b25bdd6d2def3a19c2ab/Dockerfile#L18

(Also I am building the base image with the python dependencies in the base branch and than use that image to build SearXNG core in the main branch FYI)

**Comment by dalf** [comment]
Additional comment to @mrpaulblack 's comment: `su searxng -c "/usr/bin/python3 -m searx.version freeze"` or (` ./manage pyenv.cmd python -m searx.version freeze` outside docker) creates the file `searx/version_frozen.py`

Example of content:
```
# SPDX-License-Identifier: AGPL-3.0-or-later
# this file is generated automatically by searx/version.py

VERSION_STRING = "2022.03.18-6ccd5576"
VERSION_TAG = "2022.03.18-6ccd5576"
GIT_URL = "https://github.com/searxng/searxng"
GIT_BRANCH = "master"
```

Once created, SearXNG uses this `searx/version_frozen.py` file to get the version number and GIT_URL.

From that you can update the `GIT_URL` (using `sed` or any other tool).

**Comment by codingbrock** [comment]
Thanks everyone for all the support, the version and git url should now be working. 

Please let me know if there are any further problems.
