### ISSUE TITLE
Add https://search.broker

### ISSUE THREAD

**Issue by Aethersys** [searxng/searx-instances#454]
### Requirements (make sure to read all of them)

- [X] It is my instance. I bought the domain myself and I own this domain. Free domains (e.g. Freenom) and shared domains (e.g. noip.com) are not allowed.
- [X] I'll keep my instance up to date, at the very least 1 week old. Example program for keeping up to date: watchtower, cron, ouroboros.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime or notify us [here](https://github.com/searxng/searx-instances/discussions/categories/report-instance-downtime) for a short downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I control the final webserver (software) that is serving the requests to the users of my instance. Here is a non-exhaustive list of forbidden hosting types: Cloudflare, PaaS, managed (hosting provider controlled) HTTP(S) load balancer (e.g. AWS ALB), shared Web hosting. TCP load balancer is fine. Cloudflare DNS only (grey cloud) is fine.
- [X] If needed, I can restrict users from accessing my instance for the only sole reason of keeping my instance in working conditions for the other users ([detailed description](https://github.com/searxng/searx-instances/pull/346) - evidence need to be provided when asked). Other means of restriction is forbidden.

### Bot protection requirement

- [X] Yes I have configured the `server.public_instance` parameter.

### Source code URL

https://github.com/aethersys/searxng

### Comment

Look forward to providing an instance and contributing to this excellent product.

**Comment by unixfox** [comment]
I have removed the instance until you fix this issue. There is also the fact that 2/3 of the default categories are gone, why?

**Comment by Ikbosh** [comment]
Hi @unixfox thanks for reaching out, for some reason I didn't get a notification! When running tests from my end I can see images without a problem?

Regarding Categories, I've removed them for a personally cleaner (less cluttered) experience - have I missed it somewhere where it's mentioned they're required? They're only pre-defined search criteria etc aren't they? I provide a high performance search experience for people using it to replace Google, rather than for people using all of it's meta-search functionality.

**Comment by unixfox** [comment]
well I wouldn't say that you can't do it but experience wise, you are removing quite a bit of engines from searxng ready to use. some people may get confused as to why your instance lacks of functionalities that other instances offer.

about the images not showing up I think there is an issue with your CSP, see my screenshot:
![image](https://github.com/searxng/searx-instances/assets/4016501/0740fe7b-ab0f-4b50-ba11-a96eb2a90f4a)

Either you fix the CSP or you enable "proxy" by default which will proxy the images through your server instead of letting the client load the images from google servers.

**Comment by Ikbosh** [comment]
> well I wouldn't say that you can't do it but experience wise, you are removing quite a bit of engines from searxng ready to use. some people may get confused as to why your instance lacks of functionalities that other instances offer.
> 
> about the images not showing up I think there is an issue with your CSP, see my screenshot: !
> 
> Either you fix the CSP or you enable "proxy" by default which will proxy the images through your server instead of letting the client load the images from google servers.

The confusion is a fair point - it was quicker at the time for me to just remove engines. I can instead re-categorise them on mine so that the functionality remains available via "bangs" under the "Other" category of engines? Do you think this is a fair middle ground - or is this something we should be discussing further?

Interesting on the CSP front, as it's configured identically to the docker container caddy - in saying that, noting the goal of privacy and less Google, proxying the images would be ideal. I'll run that and monitor bandwidth usage. Proxying has now been enabled.

**Comment by ononoki1** [comment]
Hi @Ikbosh, the SSL certificate of your instance has expired.

**Comment by Ikbosh** [comment]
@ononoki1 thanks Ononoki, looks to be an error with Caddy that I've now resolved. Noting that I'm still having these intermitten issues and have been holding off on migrating to a different host due to not wanting down time, how about we close this out for now without re-adding it for the time being - I get my changes done and get my monitoring working, and once I've nutted out the issues I'll post here to have it re-opened and re-added?
