### ISSUE TITLE
Add https://searx.encrypted-data.xyz

### ISSUE THREAD

**Issue by encryptedxdata** [searxng/searx-instances#85]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Your instance will be removed if you don't respect this rule.

### Bot protection

No, I have not installed a bot protection and I do recognize that without one, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by ononoki1** [comment]
Just a piece of advice: it's not recommended to use Cloudflare as reverse proxy because it MITM every request, which is a disaster for user's privacy.

**Comment by tiekoetter** [comment]
Hi @encryptedxdata,
Your instance uses Cloudflare as reverse proxy which, as @ononoki1 said, is not preferred because they MITM every request.
You also seem to have the rocket-loader.js enabled which breaks the JS on your instance.
Your [CSP](https://observatory.mozilla.org/analyze/searx.encrypted-data.xyz) config also breaks every embedded image and will prevent something like the video player from loading.
