### ISSUE TITLE
Edit https://searx.youshitsune.me

### ISSUE THREAD

**Issue by youshitsune** [searxng/searx-instances#93]
I changed my SearX instance to SearXNG and installed filtron proxy.

**Comment by tiekoetter** [comment]
@youshitsune searx.space will update this automatically. You didn't need to switch to SearXNG.

You should also look into improving your [TLS](https://cryptcheck.fr/https/searx.youshitsune.me) and [CSP](https://observatory.mozilla.org/analyze/searx.youshitsune.me) grade.

Filtron doesn't seem to be working on your instance because I can run `curl -i "https://searx.youshitsune.me/search?q=test"` and it will give me results instead of error 429.

**Comment by youshitsune** [comment]
I tried now and got 503 error

**Comment by tiekoetter** [comment]
@youshitsune Did you check the error logs?

**Comment by youshitsune** [comment]
Yes I fixed it, but filtron is installed but doesn't work.

**Comment by youshitsune** [comment]
I installed it using installation script

**Comment by youshitsune** [comment]
I can't get filtron to work it says when I run sudo ./filtron.sh install check that go_is_available command not found.

**Comment by tiekoetter** [comment]
@youshitsune Do you have golang installed on your system?

You could also try to use the limiter plugin because we will drop filtron in the near future.

**Comment by youshitsune** [comment]
Okay, thank you I am gonna try to setup limiter plugin.

**Comment by youshitsune** [comment]
I installed limiter plugin and it is working Is there anything else that I could do to make my instance's security better.

**Comment by tiekoetter** [comment]
@youshitsune Yes improving your TLS and CSP grade.

**Comment by youshitsune** [comment]
Ok, I will try to improve it.
